### ISSUE TITLE
PCRE version 8.33 doesn't exist

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy-cloudman-playbook#11]
The FTP site for PCRE source has decided to remove the 8.33 source repo.

**Comment by afgane** [comment]
Should be fixed in e87e277df5de53c33045d32a9d58f551ae063a2b. However, for future builds, I'm going to try and unify this with the rest of the project and use the package built from hree: https://github.com/galaxyproject/docker-build/tree/master/nginx
