### ISSUE TITLE
Is there a proftpd source package?

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy-cloudman-playbook#13]
The proftpd.yml tasks includes a .deb package to install on Debian family systems. I need the equivalent source package so that I can install on CentOS. Is this customized for Galaxy in some way? It looks like this is the last barrier to creating a CentOS AMI...

**Comment by afgane** [comment]
Take a look at this https://gist.github.com/afgane/9f700ba99b3bcfd7f526
It's @natefoo's creation that should help out.

**Comment by MatthewRalston** [comment]
What's the significance of the G-803372 group? Installation fails because the user_group G-803372 doesn't exist...

**Comment by natefoo** [comment]
This is the primary group of the user I build with on the system I've built the RPMs on. By default, ProFTPD will attempt to install as root, which isn't possible when doing an unprivileged user build. You should be able to set `user_group` at the top to the output of `id -gn`

**Comment by MatthewRalston** [comment]
Thanks Nate. In this repo, the installed user groups seem to be "galaxy", "docker", "postgres" and "shadow". Is it safe to assume that the "galaxy" group should have access to ProFTPD?

**Comment by natefoo** [comment]
Any of those should work, then. It just needs a valid group for that user to prevent make install from trying to install as root.

**Comment by MatthewRalston** [comment]
Thank you!
