### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy-cloudman-playbook#4]
I could not see which licence you are using in the README file, nor was a LICENSE file present as GitHub suggest: https://help.github.com/articles/open-source-licensing/

**Comment by afgane** [comment]
Added a LICENSE file (MIT) in d81f59ba9a54e707b2b4646ae0d970724f8fa39e.

**Comment by peterjc** [comment]
"Copyright (c) 2014 galaxy-iuc" ? Not Galaxy Project or similar?

**Comment by afgane** [comment]
It's all one big happy family... Updated to be Galaxy Project specifically.
