### ISSUE TITLE
"Machine Image" AMI doesn't start cloudman

### ISSUE THREAD

**Issue by kaktus42** [galaxyproject/galaxy-cloudman-playbook#7]
I created an AMI according to the README and launched a new instance with that image.
Unfortunately the CloudMan doesn't come up like in https://wiki.galaxyproject.org/CloudMan/Building (step 2)
The security groups include HTTP(S) access.
```$sudo service nginx status``` reveals: ```* nginx is not running```
ngingx-error log:
```2015/06/11 23:10:03 [emerg] 2727#0: mkdir() "/mnt/galaxy/upload_store" failed (2: No such file or directory)```

**Comment by afgane** [comment]
How are you launching the image? Are you using a launcher app?
Also, for CloudMan to come up, it needs to be bootstrapped as described here https://wiki.galaxyproject.org/CloudMan/Building#Step_4:_Hooking_it_all_up However, the default `cm.tar.gz` and `cm_boot.py` that are currently available in the `cloudman` bucket are out of date when linked to a newly built image. Instead, I'd suggest grabbing it from `cloudman-dev` bucket for the time being.

**Comment by kaktus42** [comment]
I am following the steps there: https://wiki.galaxyproject.org/CloudMan/Building
And what I understand is, to do the image building (`packer build --only amazon-ebs image.json`) and when finished, I can create a machine from the image and CloudMan will run.
> 1. Launch a new instance of the machine image created in Step 1. When CloudMan comes up, choose Test cluster as the cluster type;

You are saying now, that I should first do something from Step 4?
Where do I have to configure the path to my bucket?

Sorry - I'm not familiar at all with docker and playbooks, I'm just trying to get this running ;)
What I did is:
1. create a ec2 from ami-98aa1cf0
2. download this repo
3. run `packer build --only amazon-ebs image.json` (an AMI was created in my amazon)
4. launch a machine from that new AMI

In group_vars/all is a link which is dead. Might that be a problem?  `cm_hg_repo: https://bitbucket.org/galaxy/cloudman/raw/tip`

**Comment by afgane** [comment]
Sorry to hear you're having trouble but unfortunately this is a relatively convoluted undertaking that inevitably takes time and understanding. 

To start with, are you trying to build a custom/private version of entire *Galaxy on the Cloud* platform or just a standalone CloudMan cluster?

Regarding your specific questions, the first 3 steps should all be ok but in step 4, it is necessary to launch an instance using a launcher application such as the one available at https://launch.usegalaxy.org/ and specifying a custom AMI and a custom default bucket under the Advanced startup options. Also, newly built AMIs will are not compatible with the 'old' CloudMan (by old, I mean the currently released one that's available in the `cloudman` bucket on S3). The documentation you're reading is new and intended for the future CloudMan releases (one of which will happen any day now). So for the time being, just download `cm.tar.gz` from http://s3.amazonaws.com/cloudman-test/cm.tar.gz and `cm_boot.py` from http://s3.amazonaws.com/cloudman-test/cm_boot.py` - these are the current development/testing files - and place them in your own S3 bucket (really, unless you want to change CloudMan source, you don't need your own S3 bucket and can instead just specify `cloudman-test` as the default bucket in the Cloud Launch form and provide your custom AMI (both under the advanced startup options. This will pull the necessary files from that bucket.).

The `cm_cg_repo` variable is just a common root of a complete URL that's used in Ansible tasks so it actually works but should probably be updated to point to github instead given the recent move there.

Hope this helps - keep asking here as you have more questions.

PS
I updated the wiki page that will hopefully clarify some of the issues you raised.

**Comment by kaktus42** [comment]
The tip about the launcher page helped a lot! Thanks. I also used `cloudman-test`. When will the new version be released?

Now I'm on the way to create the galaxyFS.
Following error:

```bash
$ ansible-playbook -i inventory/builders galaxyFS.yml --extra-vars psql_galaxyftp_password=XXX --extra-vars galaxy_admin_user_password=XXX

PLAY [galaxyFS-builder] ******************************************************* 

TASK: [Assure galaxyFS dir exists] ******************************************** 
ok: [54.237.70.142]

TASK: [Assure indicesFS dir exists] ******************************************* 
changed: [54.237.70.142]

TASK: [Create shed tools dir] ************************************************* 
changed: [54.237.70.142]

TASK: [Create database dir] *************************************************** 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Initialize Galaxy database] **** 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Set Postgres port number] ****** 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Check if PostgreSQL server is running] *** 
ok: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Restart Postgres] ************** 
skipping: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Start Postgres] **************** 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Create galaxy role] ************ 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Create galaxyftp role] ********* 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.cloudman-database | Create galaxy database] ******** 
changed: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Check for Galaxy] ************************* 
ok: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Get current Galaxy changeset (hg)] ******** 
skipping: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Get current Galaxy commit id (git)] ******* 
skipping: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Report current Galaxy changeset] ********** 
skipping: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Update Galaxy to correct changeset (hg)] *** 
skipping: [54.237.70.142]

TASK: [galaxyprojectdotorg.galaxy | Update Galaxy to correct changeset (git)] *** 
fatal: [54.237.70.142] => One or more undefined variables: 'omit' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ubuntu/galaxyFS.retry

54.237.70.142              : ok=12   changed=9    unreachable=1    failed=0   

```

I checked: On the instance `git version 1.9.1` and `Mercurial Distributed SCM (version 2.8.2)` are both installed.

Further I had to adapt in `inventory/builders` the line `ansible_ssh_private_key_file` to the pem file from amazon (I uploaded it to the building instance). This should be added to the readme.

**Comment by afgane** [comment]
This is most likely an issue with the version of Ansible installed on the source machine (probably your workstation) - it should be v1.8+ (https://docs.ansible.com/playbooks_filters.html#omitting-undefined-variables-and-parameters)

I also updated the README to say the ssh key variable needs to set: ae23095a45463752809e81b4e121d62b4f0e3989

Glad to hear you're making progress.

**Comment by kaktus42** [comment]
Indeed the default package in ubuntu 14.04 is older. I installed the new version via the official PPA.

Now I'm stuck there:
```
TASK: [galaxyprojectdotorg.galaxy | Install additional Galaxy config files (static)] *** 
changed: [54.237.70.142] => (item={'dest': u'/mnt/galaxy/galaxy-app/tool-data/shared/ucsc/builds.txt', 'src': 'files/galaxy/builds.txt'})
fatal: [54.237.70.142] => input file not found at /home/ubuntu/galaxy-cloudman-playbook-master/roles/galaxyprojectdotorg.galaxy/files/files/shed_tool_conf.xml.cloud or /home/ubuntu/galaxy-cloudman-playbook-master/files/shed_tool_conf.xml.cloud
```

Maybe important here: I disabled to install tools (`cm_install_tools: no`).
The location `/home/ubuntu/galaxy-cloudman-playbook-master/roles/galaxyprojectdotorg.galaxy/files/files` does not exist. The loaction `/home/ubuntu/galaxy-cloudman-playbook-master/files` is the correct one, but does not contain a shed_tool_conf.xml.cloud:
```
$ ll /home/ubuntu/galaxy-cloudman-playbook-master/files/
total 52
-rw-rw-r-- 1 ubuntu ubuntu   433 May 28 22:11 dbkeys_list.yaml.cloud
drwxrwxr-x 2 ubuntu ubuntu  4096 May 28 22:11 galaxy/
-rw-rw-r-- 1 ubuntu ubuntu 35676 May 28 22:11 shed_tool_list.yaml
$ ll /home/ubuntu/galaxy-cloudman-playbook-master/files/galaxy/
total 68
-rw-rw-r-- 1 ubuntu ubuntu 57020 May 28 22:11 builds.txt
-rw-rw-r-- 1 ubuntu ubuntu   221 May 28 22:11 tool_sheds_conf.xml
```

Another thing for clarification: The indicies listed in `files/galaxy/builds.txt` will not be installed, when I set `cm_install_data: no`, correct?

**Comment by afgane** [comment]
Ahh, yeah, I forgot to commit the missing file earlier - sorry. I added it now (3ef7602d545f003d7b3a98a51dc6a01cc6b1e886) so just pull the changes and rerun it.

And setting `cm_install_tools` and `cm_install_data` to `no` will skip both of those sections. `builds.txt` is the list of the genomes what will be 'known' to Galaxy but they won't get installed. 
(fyi, when you get to the data installation step, unfortunately the currently implemented method is too naive and it will not work; instead it will need to be done manually and/or via Data Managers - that's what we've resorted to for the time being).

**Comment by kaktus42** [comment]
Thank you!
I got it all together so far. I also created a new Volume `galaxyIndices` and put my genomes in there.
Then I updated/created the loc files in `/mnt/galaxy/galaxy-app/tool-data`

I'm now unsure about how to proceed. It seems I have to create an own bucket where I put the cloudman source and the *snaps.yaml* - but then I have to update this bucket always when I want to update this Instance, correct?
Is there a way to just publish the *snaps.yaml* only?

And to be sure all together: *snaps.yaml* contains the information for the galaxy installation (galaxyFS) and my galaxyIndices (as a snapshot).
The archive of my galaxyFS exists already in my bucket, the created galaxyIndices is snapshotted (manually on AWS console).
So my snaps should look like following?
```yml
version: 1
clouds:
  - name: amazon
    regions:
    - deployments:
      - name: GalaxyCloud
        filesystems:
        - name: galaxy
          roles: galaxyTools,galaxyData
          archive_url: http://s3.amazonaws.com/galaxy-cip/fs-archives/galaxyFS-latest.tar.gz
          type: archive
          size: 10
        - name: galaxyIndices
          roles: galaxyIndices
          snap_id: snap-89a47ef8
        default_mi: ami-63b34408
        bucket: cloudman
      name: us-east-1
```
I adapted `archive_url`, `snap_id`, `default_mi`.

This question might be a little far from this repository now, but do I have to persist the galaxy and galaxyIndices? What does that do and when should I do that?
I am still trying to get all together in my head now ;) - that's what this step is for, right?

Maybe I should have answered your question from before:
> To start with, are you trying to build a custom/private version of entire Galaxy on the Cloud platform or just a standalone CloudMan cluster?

I would like to create a customized CloudMan cluster with galaxy, so I have my genomes and tools installed when I start a new cluster. I don't want to adapt cloudman code (though I'd like to have the new version with customizable nodes)

I also thought about going this way: https://wiki.galaxyproject.org/CloudMan/CustomizeGalaxyCloud, but I like to have a clean start. But what is the difference now and to a customized *persistent_data.yaml* in the link? Nothing, because I didn't change the cloudman source files?

Sorry that I'm a little confused now...

**Comment by afgane** [comment]
> I'm now unsure about how to proceed. It seems I have to create an own bucket where I put the cloudman source and the `snaps.yaml` - but then I have to update this bucket always when I want to update this Instance, correct?
Yes, you'll need your own bucket with `snaps.yaml` that contains the the snapshot ID you created for the indices file system and the galaxy file system archive URL (assuming you've just stuck with the default playbook behavior and created a file system archive). That bucket will also need to contain `cm_boot.py` as pointed out earlier in this thread. You'll only need update the contents of `snaps.yaml` when you change the snapshot ID.

> Is there a way to just publish the `snaps.yaml` only?
I'm afraid no. The plan is to get rid of this dependency on an external bucket but that has not been implemented yet (see this Trello card to follow along or help if you’d like: https://trello.com/c/ItNoBVf3)

Your `snaps.yaml` looks fine. You should probably just change `bucket` line to `bucket: galaxy-cip`

Re. persisting galaxy & indices FSs - you mean from within CloudMan's Admin page? That's used when you launch your own stock cluster and make changes to the indices FS. Then, the next time you launch that same cluster, those changes will have persisted. Otherwise, you will get a new volume that gets created from the stock snapshot as defined in `snaps.yaml`. Basically, if you’d like to be able to create different clusters that have a common base, what you're doing (i.e., building the pieces) is the best option. 
I hope that covers it. If not, let me know.

**Comment by kaktus42** [comment]
Not quite yet.
I put all the files in the bucket and tried to start an instance with the launcher-site.
I defined Default bucket: galaxy-cip
And I chose my own image (created before).

The instance started, but this is weird now: I can't use my password for accessing the cloud console. I created two instances now. As username I use some arbitrary value, as password the password I supplied.

Here the generated userdata:
```
access_key: !!python/unicode '###'
bucket_default: !!python/unicode 'galaxy-cip'
cloud_name: !!python/unicode 'Amazon'
cluster_name: !!python/unicode 'CIP Test'
custom_image_id: !!python/unicode 'ami-63b34408'
extra_user_data: !!python/unicode ''
flavor_id: !!python/unicode ''
freenxpass: !!python/unicode '###'
instance_type: !!python/unicode 'm3.medium'
key_pair: !!python/unicode 'cloudman'
password: !!python/unicode '###'
public_ip: null
secret_key: !!python/unicode '###'
task_id: 405ad5a5-d5bd-479f-b5f8-253bc5ec5bb7

cloud_type: !!python/unicode 'ec2'
ec2_conn_path: !!python/unicode '/'
ec2_port: null
is_secure: true
region_endpoint: !!python/unicode 'ec2.amazonaws.com'
region_name: !!python/unicode 'us-east-1'
s3_conn_path: !!python/unicode '/'
s3_host: !!python/unicode 's3.amazonaws.com'
s3_port: null
```

Something wrong with the image?

**Comment by kaktus42** [comment]
solved. User must be `ubuntu` now. This apparently has changed. Found it in the nginx files.

**Comment by kaktus42** [comment]
I think this can be closed now.
It works so far, although there are still some problems.
But I think they don't belong in this issue.
Thank you very much for all your help!

**Comment by afgane** [comment]
No problem. Thanks for following through with and the giving feedback on the process. Let me know when you have more questions.

**Comment by amaclean199** [comment]
I have made a Cloudman image in my private Openstack environment but how can I initially launch it as mentioned in Step 2.1:

>Launch a new instance of the machine image created in Step 1 using Cloud Launch (either the one available at https://launch.usegalaxy.org/ or a privately deployed one). When CloudMan comes up, choose Test cluster as the cluster type;

Since it's not with Amazon I can't use https://launch.usegalaxy.org/ but it needs to be running in order to proceed to Step 2.2:

>From CloudMan's Admin page, add a new volume-based file system called galaxy of desired size (default 10GB);

**Comment by afgane** [comment]
You'll need to setup your own instance of the Cloud Launch application: https://github.com/galaxyproject/cloudlaunch
It shouldn’t' be more than ~half a dozen copy&paste commands from the top of the README there.

(it's in the plans to allow users to define their own clouds and images on the main launch.usegalaxy.org site but that'll take some development time, I'm afraid)
